#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import argparse

from json import load as json_load
from sdk.build import buildAll
from shutil import rmtree

from sdk.utils import downloadFile, json


def bootSystem(cfg: json):
    downloadFile(
        "https://retrage.github.io/edk2-nightly/bin/DEBUGX64_OVMF.fd", "bios", False
    )
    os.system(
        f"{cfg['qemu-exec']} -bios {os.path.join(os.path.dirname(os.path.realpath(__file__)), 'bios')} {' '.join(cfg['qemuflags'])} -drive file=fat:rw:{os.path.join(os.path.dirname(os.path.realpath(__file__)), '.build', 'sysroot')},media=disk,format=raw"
    )


def bootSystemLegacy(cfg: json):
    os.system(
        f"xorriso -as mkisofs -b /boot/limine-cd.bin \
		-no-emul-boot -boot-load-size 4 -boot-info-table \
		--efi-boot /boot/limine-cd-efi.bin \
		-efi-boot-part --efi-boot-image --protective-msdos-label \
		{os.path.join(os.path.dirname(os.path.realpath(__file__)), '.build', 'sysroot')} -o navy.iso"
    )

    if not os.path.isfile("./limine-deploy"):
        downloadFile(
            "https://raw.githubusercontent.com/limine-bootloader/limine/v3.5.4-binary/limine-deploy.c",
            "limine-deploy.c",
            False,
        )
        downloadFile(
            "https://raw.githubusercontent.com/limine-bootloader/limine/v3.5.4-binary/limine-hdd.h",
            "limine-hdd.h",
            False,
        )
        os.system(
            "cc -g -O2 -pipe -Wall -Wextra -std=c99 limine-deploy.c -o limine-deploy"
        )
        os.remove("limine-deploy.c")
        os.remove("limine-hdd.h")

    os.system("./limine-deploy ./navy.iso")
    os.system(f"{cfg['qemu-exec']} {' '.join(cfg['qemuflags'])} -cdrom navy.iso")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Navy Build System")

    parser.add_argument(
        "-b", "--build", action="store_true", help="Compile the Navy system"
    )
    parser.add_argument(
        "-B", "--boot", action="store_true", help="Boot the system using QEMU"
    )

    parser.add_argument(
        "-l",
        "--legacy",
        action="store_true",
        help="Boot the system in legacy mode using QEMU",
    )

    parser.add_argument(
        "-c", "--clean", action="store_true", help="Clean the build directory"
    )
    parser.add_argument(
        "-n", "--nuke", action="store_true", help="Nuke the project! Like in fallout"
    )

    args = parser.parse_args()

    if not sum(vars(args).values()):
        parser.print_help()

    cfgFile = open(
        os.path.join(os.path.dirname(os.path.realpath(__file__)), "sdk", "config.json")
    )

    cfg = json_load(cfgFile)

    if args.build:
        buildAll(cfg)
        os.system("ninja")

    if args.clean:
        rmtree(".build")

    if args.boot:
        buildAll(cfg)
        if os.system("ninja") != 0:
            exit(1)

        bootSystem(cfg)

    if args.legacy:
        buildAll(cfg)

        if os.system("ninja") != 0:
            exit(1)

        bootSystemLegacy(cfg)

    if args.nuke:
        try:
            os.remove("build.ninja")
            rmtree(".build")
        except FileNotFoundError:
            pass
